
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Afganistan','Afghanistan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Albania','Albania');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Algieria','Algeria');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Andora','Andorra');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Angola','Angola');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Anguilla','Anguilla');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Antarktyka','Antarctica');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Antigua i Barbuda','Antigua and Barbuda');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Arabia Saudyjska','Saudi Arabia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Argentyna','Argentina');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Armenia','Armenia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Aruba','Aruba');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Australia','Australia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Austria','Austria');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Azerbejdżan','Azerbaijan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Bahamy','Bahamas');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Bahrajn','Bahrain');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Bangladesz','Bangladesh');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Barbados','Barbados');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Belgia','Belgium');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Belize','Belize');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Benin','Benin');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Bermudy','Bermuda');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Bhutan','Bhutan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Białoruś','Belarus');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Boliwia','Bolivia, Plurinational State of');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Bonaire, Sint Eustatius i Saba','Bonaire, Sint Eustatius and Saba');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Bośnia i Hercegowina','Bosnia and Herzegovina');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Botswana','Botswana');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Brazylia','Brazil');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Brunei','Brunei Darussalam');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Brytyjskie Terytorium Oceanu Indyjskiego','British Indian Ocean Territory');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Brytyjskie Wyspy Dziewicze','Virgin Islands, British');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Bułgaria','Bulgaria');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Burkina Faso','Burkina Faso');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Burundi','Burundi');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Chile','Chile');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Chiny','China');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Chorwacja','Croatia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Curaçao','Curaçao');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Cypr','Cyprus');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Czad','Chad');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Czarnogóra','Montenegro');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Czechy','Czech Republic');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Dalekie Wyspy Mniejsze Stanów Zjednoczonych','United States Minor Outlying Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Dania','Denmark');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Demokratyczna Republika Konga','Congo, the Democratic Republic of the');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Dominika','Dominica');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Dominikana','Dominican Republic');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Dżibuti','Djibouti');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Egipt','Egypt');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Ekwador','Ecuador');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Erytrea','Eritrea');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Estonia','Estonia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Etiopia','Ethiopia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Falklandy','Falkland Islands (Malvinas)');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Fidżi','Fiji');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Filipiny','Philippines');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Finlandia','Finland');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Francja','France');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Francuskie Terytoria Południowe i Antarktyczne','French Southern Territories');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gabon','Gabon');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gambia','Gambia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Georgia Południowa i Sandwich Południowy','South Georgia and the South Sandwich Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Ghana','Ghana');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gibraltar','Gibraltar');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Grecja','Greece');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Grenada','Grenada');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Grenlandia','Greenland');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gruzja','Georgia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Guam','Guam');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Guernsey','Guernsey');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gujana Francuska','French Guiana');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gujana','Guyana');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gwadelupa','Guadeloupe');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gwatemala','Guatemala');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gwinea Bissau','Guinea-Bissau');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gwinea Równikowa','Equatorial Guinea');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Gwinea','Guinea');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Haiti','Haiti');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Hiszpania','Spain');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Holandia','Netherlands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Honduras','Honduras');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Hongkong','Hong Kong');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Indie','India');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Indonezja','Indonesia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Irak','Iraq');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Iran','Iran, Islamic Republic of');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Irlandia','Ireland');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Islandia','Iceland');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Izrael','Israel');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Jamajka','Jamaica');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Japonia','Japan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Jemen','Yemen');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Jersey','Jersey');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Jordania','Jordan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kajmany','Cayman Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kambodża','Cambodia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kamerun','Cameroon');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kanada','Canada');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Katar','Qatar');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kazachstan','Kazakhstan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kenia','Kenya');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kirgistan','Kyrgyzstan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kiribati','Kiribati');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kolumbia','Colombia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Komory','Comoros');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kongo','Congo');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Korea Południowa','Korea, Republic of');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Korea Północna','Korea, Democratic People''s Republic of');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kostaryka','Costa Rica');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kuba','Cuba');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Kuwejt','Kuwait');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Laos','Lao People''s Democratic Republic');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Lesotho','Lesotho');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Liban','Lebanon');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Liberia','Liberia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Libia','Libyan Arab Jamahiriya');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Liechtenstein','Liechtenstein');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Litwa','Lithuania');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Luksemburg','Luxembourg');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Łotwa','Latvia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Macedonia','Macedonia, the former Yugoslav Republic of');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Madagaskar','Madagascar');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Majotta','Mayotte');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Makau','Macao');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Malawi','Malawi');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Malediwy','Maldives');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Malezja','Malaysia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Mali','Mali');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Malta','Malta');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Mariany Północne','Northern Mariana Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Maroko','Morocco');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Martynika','Martinique');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Mauretania','Mauritania');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Mauritius','Mauritius');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Meksyk','Mexico');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Mikronezja','Micronesia, Federated States of');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Mjanma','Myanmar');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Mołdawia','Moldova, Republic of');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Monako','Monaco');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Mongolia','Mongolia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Montserrat','Montserrat');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Mozambik','Mozambique');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Namibia','Namibia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Nauru','Nauru');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Nepal','Nepal');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Niemcy','Germany');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Niger','Niger');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Nigeria','Nigeria');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Nikaragua','Nicaragua');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Niue','Niue');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Norfolk','Norfolk Island');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Norwegia','Norway');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Nowa Kaledonia','New Caledonia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Nowa Zelandia','New Zealand');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Oman','Oman');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Pakistan','Pakistan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Palau','Palau');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Palestyna','Palestinian Territory, Occupied');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Panama','Panama');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Papua-Nowa Gwinea','Papua New Guinea');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Paragwaj','Paraguay');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Peru','Peru');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Pitcairn','Pitcairn');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Polinezja Francuska','French Polynesia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Polska','Poland');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Portoryko','Puerto Rico');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Portugalia','Portugal');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Republika Południowej Afryki','South Africa');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Republika Środkowoafrykańska','Central African Republic');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Republika Zielonego Przylądka','Cape Verde');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Reunion','Réunion');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Rosja','Russian Federation');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Rumunia','Romania');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Rwanda','Rwanda');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Sahara Zachodnia','Western Sahara');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Saint Kitts i Nevis','Saint Kitts and Nevis');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Saint Lucia','Saint Lucia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Saint Vincent i Grenadyny','Saint Vincent and the Grenadines');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Saint-Barthélemy','Saint Barthélemy');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Saint-Martin','Saint Martin (French part)');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Saint-Pierre i Miquelon','Saint Pierre and Miquelon');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Salwador','El Salvador');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Samoa Amerykańskie','American Samoa');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Samoa','Samoa');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('San Marino','San Marino');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Senegal','Senegal');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Serbia','Serbia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Seszele','Seychelles');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Sierra Leone','Sierra Leone');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Singapur','Singapore');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Sint Maarten','Sint Maarten (Dutch part)');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Słowacja','Slovakia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Słowenia','Slovenia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Somalia','Somalia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Sri Lanka','Sri Lanka');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Stany Zjednoczone','United States');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Suazi','Swaziland');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Sudan','Sudan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Sudan Południowy','South Sudan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Surinam','Suriname');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Svalbard i Jan Mayen','Svalbard and Jan Mayen');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Syria','Syrian Arab Republic');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Szwajcaria','Switzerland');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Szwecja','Sweden');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Tadżykistan','Tajikistan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Tajlandia','Thailand');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Tajwan','Taiwan, Province of China');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Tanzania','Tanzania, United Republic of');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Timor Wschodni','Timor-Leste');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Togo','Togo');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Tokelau','Tokelau');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Tonga','Tonga');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Trynidad i Tobago','Trinidad and Tobago');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Tunezja','Tunisia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Turcja','Turkey');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Turkmenistan','Turkmenistan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Turks i Caicos','Turks and Caicos Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Tuvalu','Tuvalu');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Uganda','Uganda');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Ukraina','Ukraine');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Urugwaj','Uruguay');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Uzbekistan','Uzbekistan');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Vanuatu','Vanuatu');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wallis i Futuna','Wallis and Futuna');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Watykan','Holy See (Vatican City State)');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wenezuela','Venezuela, Bolivarian Republic of');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Węgry','Hungary');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wielka Brytania','United Kingdom');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wietnam','Viet Nam');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Włochy','Italy');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wybrzeże Kości Słoniowej','Côte d''Ivoire');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspa Bouveta','Bouvet Island');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspa Bożego Narodzenia','Christmas Island');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspa Man','Isle of Man');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha','Saint Helena, Ascension and Tristan Cunha');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspy Alandzkie','Åland Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspy Cooka','Cook Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspy Dziewicze Stanów Zjednoczonych','Virgin Islands, U.S.');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspy Heard i McDonalda','Heard Island and McDonald Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspy Kokosowe','Cocos (Keeling) Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspy Marshalla','Marshall Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspy Owcze','Faroe Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspy Salomona','Solomon Islands');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Wyspy Świętego Tomasza i Książęca','Sao Tome and Principe');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Zambia','Zambia');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Zimbabwe','Zimbabwe');
INSERT INTO Kraj(NazwaPL,NazwaEN) VALUES ('Zjednoczone Emiraty Arabskie','United Arab Emirates');
